apiVersion: v1
kind: Service
metadata:
  name: schloss-service
spec:
  selector:
    app: schloss
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
